# Generated by Django 5.2.8 on 2025-12-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMillionsDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(db_index=True)),
                ('ball_1', models.PositiveSmallIntegerField()),
                ('ball_2', models.PositiveSmallIntegerField()),
                ('ball_3', models.PositiveSmallIntegerField()),
                ('ball_4', models.PositiveSmallIntegerField()),
                ('ball_5', models.PositiveSmallIntegerField()),
                ('bonus_ball', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('megaplier', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mega Millions Draw',
                'verbose_name_plural': 'Mega Millions Draws',
            },
        ),
        migrations.CreateModel(
            name='PowerBallDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(db_index=True)),
                ('ball_1', models.PositiveSmallIntegerField()),
                ('ball_2', models.PositiveSmallIntegerField()),
                ('ball_3', models.PositiveSmallIntegerField()),
                ('ball_4', models.PositiveSmallIntegerField()),
                ('ball_5', models.PositiveSmallIntegerField()),
                ('bonus_ball', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('multiplier', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Powerball Draw',
                'verbose_name_plural': 'Powerball Draws',
            },
        ),
    ]
