# Generated by Django 5.2.8 on 2025-12-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMillionsDrawPositionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(db_index=True)),
                ('ball_1', models.CharField(choices=[('0D-30', 'Overdue - Drawn 30+ Days Ago'), ('OD-60', 'Overdue - Drawn 60+ Days Ago'), ('OD-90', 'Overdue - Drawn 90+ Days Ago'), ('HOT-30', 'Hot - Most Drawn Last 30 Days'), ('HOT-60', 'Hot - Most Drawn Last 60 Days'), ('HOT-90', 'Hot - Most Drawn Last 90 Days'), ('UNCATEGORIZED', 'Previously Uncategorized')], default='UNCATEGORIZED', max_length=15)),
                ('ball_2', models.CharField(choices=[('0D-30', 'Overdue - Drawn 30+ Days Ago'), ('OD-60', 'Overdue - Drawn 60+ Days Ago'), ('OD-90', 'Overdue - Drawn 90+ Days Ago'), ('HOT-30', 'Hot - Most Drawn Last 30 Days'), ('HOT-60', 'Hot - Most Drawn Last 60 Days'), ('HOT-90', 'Hot - Most Drawn Last 90 Days'), ('UNCATEGORIZED', 'Previously Uncategorized')], default='UNCATEGORIZED', max_length=15)),
                ('ball_3', models.CharField(choices=[('0D-30', 'Overdue - Drawn 30+ Days Ago'), ('OD-60', 'Overdue - Drawn 60+ Days Ago'), ('OD-90', 'Overdue - Drawn 90+ Days Ago'), ('HOT-30', 'Hot - Most Drawn Last 30 Days'), ('HOT-60', 'Hot - Most Drawn Last 60 Days'), ('HOT-90', 'Hot - Most Drawn Last 90 Days'), ('UNCATEGORIZED', 'Previously Uncategorized')], default='UNCATEGORIZED', max_length=15)),
                ('ball_4', models.CharField(choices=[('0D-30', 'Overdue - Drawn 30+ Days Ago'), ('OD-60', 'Overdue - Drawn 60+ Days Ago'), ('OD-90', 'Overdue - Drawn 90+ Days Ago'), ('HOT-30', 'Hot - Most Drawn Last 30 Days'), ('HOT-60', 'Hot - Most Drawn Last 60 Days'), ('HOT-90', 'Hot - Most Drawn Last 90 Days'), ('UNCATEGORIZED', 'Previously Uncategorized')], default='UNCATEGORIZED', max_length=15)),
                ('ball_5', models.CharField(choices=[('0D-30', 'Overdue - Drawn 30+ Days Ago'), ('OD-60', 'Overdue - Drawn 60+ Days Ago'), ('OD-90', 'Overdue - Drawn 90+ Days Ago'), ('HOT-30', 'Hot - Most Drawn Last 30 Days'), ('HOT-60', 'Hot - Most Drawn Last 60 Days'), ('HOT-90', 'Hot - Most Drawn Last 90 Days'), ('UNCATEGORIZED', 'Previously Uncategorized')], default='UNCATEGORIZED', max_length=15)),
                ('bonus_ball', models.CharField(choices=[('0D-30', 'Overdue - Drawn 30+ Days Ago'), ('OD-60', 'Overdue - Drawn 60+ Days Ago'), ('OD-90', 'Overdue - Drawn 90+ Days Ago'), ('HOT-30', 'Hot - Most Drawn Last 30 Days'), ('HOT-60', 'Hot - Most Drawn Last 60 Days'), ('HOT-90', 'Hot - Most Drawn Last 90 Days'), ('UNCATEGORIZED', 'Previously Uncategorized')], default='UNCATEGORIZED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mega Millions Draw Position Tracker',
                'verbose_name_plural': 'Mega Millions Draw Position Tracker',
            },
        ),
        migrations.CreateModel(
            name='PowerBallDrawPositionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(db_index=True)),
                ('ball_1', models.CharField(choices=[('0D-30', 'Overdue - Drawn 30+ Days Ago'), ('OD-60', 'Overdue - Drawn 60+ Days Ago'), ('OD-90', 'Overdue - Drawn 90+ Days Ago'), ('HOT-30', 'Hot - Most Drawn Last 30 Days'), ('HOT-60', 'Hot - Most Drawn Last 60 Days'), ('HOT-90', 'Hot - Most Drawn Last 90 Days'), ('UNCATEGORIZED', 'Previously Uncategorized')], default='UNCATEGORIZED', max_length=15)),
                ('ball_2', models.CharField(choices=[('0D-30', 'Overdue - Drawn 30+ Days Ago'), ('OD-60', 'Overdue - Drawn 60+ Days Ago'), ('OD-90', 'Overdue - Drawn 90+ Days Ago'), ('HOT-30', 'Hot - Most Drawn Last 30 Days'), ('HOT-60', 'Hot - Most Drawn Last 60 Days'), ('HOT-90', 'Hot - Most Drawn Last 90 Days'), ('UNCATEGORIZED', 'Previously Uncategorized')], default='UNCATEGORIZED', max_length=15)),
                ('ball_3', models.CharField(choices=[('0D-30', 'Overdue - Drawn 30+ Days Ago'), ('OD-60', 'Overdue - Drawn 60+ Days Ago'), ('OD-90', 'Overdue - Drawn 90+ Days Ago'), ('HOT-30', 'Hot - Most Drawn Last 30 Days'), ('HOT-60', 'Hot - Most Drawn Last 60 Days'), ('HOT-90', 'Hot - Most Drawn Last 90 Days'), ('UNCATEGORIZED', 'Previously Uncategorized')], default='UNCATEGORIZED', max_length=15)),
                ('ball_4', models.CharField(choices=[('0D-30', 'Overdue - Drawn 30+ Days Ago'), ('OD-60', 'Overdue - Drawn 60+ Days Ago'), ('OD-90', 'Overdue - Drawn 90+ Days Ago'), ('HOT-30', 'Hot - Most Drawn Last 30 Days'), ('HOT-60', 'Hot - Most Drawn Last 60 Days'), ('HOT-90', 'Hot - Most Drawn Last 90 Days'), ('UNCATEGORIZED', 'Previously Uncategorized')], default='UNCATEGORIZED', max_length=15)),
                ('ball_5', models.CharField(choices=[('0D-30', 'Overdue - Drawn 30+ Days Ago'), ('OD-60', 'Overdue - Drawn 60+ Days Ago'), ('OD-90', 'Overdue - Drawn 90+ Days Ago'), ('HOT-30', 'Hot - Most Drawn Last 30 Days'), ('HOT-60', 'Hot - Most Drawn Last 60 Days'), ('HOT-90', 'Hot - Most Drawn Last 90 Days'), ('UNCATEGORIZED', 'Previously Uncategorized')], default='UNCATEGORIZED', max_length=15)),
                ('bonus_ball', models.CharField(choices=[('0D-30', 'Overdue - Drawn 30+ Days Ago'), ('OD-60', 'Overdue - Drawn 60+ Days Ago'), ('OD-90', 'Overdue - Drawn 90+ Days Ago'), ('HOT-30', 'Hot - Most Drawn Last 30 Days'), ('HOT-60', 'Hot - Most Drawn Last 60 Days'), ('HOT-90', 'Hot - Most Drawn Last 90 Days'), ('UNCATEGORIZED', 'Previously Uncategorized')], default='UNCATEGORIZED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Powerball Draw Position Tracker',
                'verbose_name_plural': 'Powerball Draw Position Tracker',
            },
        ),
    ]
